### ISSUE TITLE
Как правильно сделать pull request?

### ISSUE THREAD

**Issue by lazyphpdev** [dle-modules/DLE-LinkEnso#2]
Переписал модуль, но как сюда правильно сделать pull request не знаю... @pafnuty 
Сильно не бейте, не работаю я с git :sob:

**Comment by pafnuty** [comment]
@lazyphpdev Привет! Всё достаточно просто:
1) Клонируешь репозиторий (кнопка "Fork")
2) Делаешь нужные изменения (в т.ч. readme и прочие файлы)
3) Отправляешь PR в основной репозиторий.
Если вдруг не получится, пиши - помогу.
